cat_config = {
    "id":1,
    "hp": 100,
    "atk": 90,
    "speed": 1,
    "color": (255, 255, 0),
    "attack_range": 50,
    "is_aoe": True,
    "kb_limit": 5,
    "cooldown": 5000,
    "cost": 150,
    "width": 200,
    "height": 200,
    "windup_duration": 200,
    "attack_duration": 100,
    "recovery_duration": 200,
    "attack_interval": 1000,
    "idle_frames": ["cat_folder/basic/attacking/basic_snail.png"],
    "move_frames": ["cat_folder/basic/attacking/basic_snail.png",
                    "cat_folder/basic/walking/basic_snail_walking1.png",
                    "cat_folder/basic/walking/basic_snail_walking2.png",
                    "cat_folder/basic/walking/basic_snail_walking1.png"],
    "windup_frames": ["cat_folder/basic/attacking/basic_snail_attcking1.png",
                      "cat_folder/basic/attacking/basic_snail_attcking2.png" ],
    "attack_frames": ["cat_folder/basic/attacking/basic_snail_attcking3.png",],
    "recovery_frames": [ "cat_folder/basic/attacking/basic_snail_attcking2.png",
                        "cat_folder/basic/attacking/basic_snail_attcking1.png"],
    "kb_frames": ["cat_folder/basic/attacking/basic_snail.png"],
    "ibtn_idle": "cat_folder/basic/ibtn_idle.png",
    "ibtn_hover": "ccat_folder/basic/ibtn_hover.png",
    "ibtn_pressed": "cat_folder/basic/ibtn_pressed.png",
    "attack_type": "physic",  # 攻擊類型
    "cat_image": "cat_folder/basic/cat_image.png",  # 放在levelselection的貓咪圖片
}