cat_config = {
    "id":5,
    "hp": 500,
    "atk": 10,
    "speed": 1,
    "color": (255, 0, 255),
    "attack_range": 180,
    "is_aoe": True,
    "kb_limit": 1,
    "cooldown": 8000,
    "cost": 660,
    "width": 240,
    "height": 240,
    "windup_duration": 200,
    "attack_duration": 200,
    "recovery_duration": 200,
    "attack_interval": 3000,
    "idle_frames": ["cat_folder/tank/attacking/tank.png"],
    "move_frames": ["cat_folder/tank/attacking/tank.png",
                    "cat_folder/tank/walking/tank-walking1.png",
                    "cat_folder/tank/walking/tank-walking2.png",
                    "cat_folder/tank/walking/tank-walking1.png",],
    "windup_frames": ["cat_folder/tank/attacking/tank-attacking1.png",
                      "cat_folder/tank/attacking/tank-attacking2.png"],
    "attack_frames": ["cat_folder/tank/attacking/tank-attacking3.png",
                      "cat_folder/tank/attacking/tank-attacking4.png",
                      "cat_folder/tank/attacking/tank-attacking3.png"],
    "recovery_frames": ["cat_folder/tank/attacking/tank-attacking2.png",
                        "cat_folder/tank/attacking/tank-attacking1.png"],
    "kb_frames": [],
    "delta_y": 7,  # 微調 y 座標
    "ibtn_idle": "cat_folder/tank/ibtn_idle.png",
    "ibtn_hover": "ccat_folder/tank/ibtn_hover.png",
    "ibtn_pressed": "cat_folder/tank/ibtn_pressed.png",
    "attack_type": "physic",  # 攻擊類型
    "cat_image": "cat_folder/tank/cat_image.png",  # 放在levelselection的貓咪圖片
}