cat_config = {
    "id":4,
    "hp": 300,
    "atk": 120,
    "speed": 3,
    "color": (0, 255, 255),
    "attack_range": 80,
    "is_aoe": False,
    "kb_limit": 3,
    "cooldown": 4000,
    "cost": 120,
    "width": 200,
    "height": 200,
    "windup_duration": 200,
    "attack_duration": 100,
    "recovery_duration": 200,
    "attack_interval": 2000,
    "idle_frames": ["cat_folder/speedy/walking/speedy.png"],
    "move_frames": ["cat_folder/speedy/walking/speedy.png",
                    "cat_folder/speedy/walking/speedy-walking1.png",
                    "cat_folder/speedy/walking/speedy-walking2.png",
                    "cat_folder/speedy/walking/speedy-walking1.png"],
    "windup_frames": ["cat_folder/speedy/attacking/speedy-attacking1.png",
                      "cat_folder/speedy/attacking/speedy-attacking2.png"],
    "attack_frames": ["cat_folder/speedy/attacking/speedy-attacking3.png"],
    "recovery_frames": ["cat_folder/speedy/attacking/speedy-attacking2.png",
                        "cat_folder/speedy/attacking/speedy-attacking1.png"],
    "kb_frames": ["cat_folder/speedy/walking/speedy.png"],
    "ibtn_idle": "cat_folder/speedy/ibtn_idle.png",
    "ibtn_hover": "ccat_folder/speedy/ibtn_hover.png",
    "ibtn_pressed": "cat_folder/speedy/ibtn_pressed.png",
    "attack_type": "electric",  # 攻擊類型
    "cat_image": "cat_folder/speedy/cat_image.png",  # 放在levelselection的貓咪圖片
}